"""
Pretty-print the tree generated by the LAL frontend from the "test.adb" input
file.
"""

import lalcheck.ai.irs.basic.frontends.lal as lal2basic

import test_helper
from lalcheck.ai.irs.basic.tools import PrettyPrinter


@test_helper.run
def run(args):
    ctx = lal2basic.ExtractionContext()

    progs = ctx.extract_programs_from_file("test.adb")

    output = PrettyPrinter.pretty_print(
        test_helper.find_test_program(progs, args.test_subprogram),
        PrettyPrinter.Opts(print_ids=True)
    )

    print(output)
