"""
Pretty-print the tree generated by the LAL frontend from the "test.adb" input
file.
"""

import lalcheck.irs.basic.frontends.lal as lal2basic
from lalcheck.irs.basic.tools import PrettyPrinter
import test_helper


@test_helper.run
def run(args):
    ctx = lal2basic.ExtractionContext()

    progs = ctx.extract_programs_from_file("test.adb")

    output = PrettyPrinter.pretty_print(
        progs[0],
        PrettyPrinter.Opts(print_ids=True)
    )

    print(output)
